Add files via upload

diff --git a/analysis/Makefile b/analysis/Makefile
--- a/analysis/Makefile
+++ b/analysis/Makefile
@@ -49,18 +49,22 @@ cleanall:
 
 run_specified:
 ifndef INPUT
-	$(error INPUT variable is not set. Usage: make run INPUT=... OUTPUT=...)
+	$(error INPUT variable is not set. Usage: make run INPUT=... OUTPUT=... OUTPUT_ML=...)
 endif
 ifndef OUTPUT
-	$(error OUTPUT variable is not set. Usage: make run INPUT=... OUTPUT=...)
+	$(error OUTPUT variable is not set. Usage: make run INPUT=... OUTPUT=... OUTPUT_ML=...)
 endif
-	$(BIN_DIR)/$(PROGRAM) $(INPUT) $(OUTPUT)
+ifndef OUTPUT_ML
+	$(error OUTPUT_ML variable is not set. Usage: make run INPUT=... OUTPUT=... OUTPUT_ML=...)
+endif
+	$(BIN_DIR)/$(PROGRAM) $(INPUT) $(OUTPUT) $(OUTPUT_ML)
 
 #INPUT  := "/Volumes/Sandisk_Macbook_Pro_1tb/electron_muon_project/data/jpsi_psi2s_extra_variables.root"
 INPUT  := "/Volumes/Sandisk_Macbook_Pro_1tb/electron_muon_project/data/data23_2trk_moreTCvars.root"
 OUTPUT := "/Volumes/Sandisk_Macbook_Pro_1tb/electron_muon_project/out/out_hists_data23.root"
+OUTPUT_ML := "/Volumes/Sandisk_Macbook_Pro_1tb/electron_muon_project/out/out_ml_data23.root"
 run:
-	$(BIN_DIR)/$(PROGRAM) $(INPUT) $(OUTPUT)
+	$(BIN_DIR)/$(PROGRAM) $(INPUT) $(OUTPUT) $(OUTPUT_ML)
 
 
 PLOT_INPUT  := /Volumes/Sandisk_Macbook_Pro_1tb/electron_muon_project/out/out_hists_data23.root
@@ -68,6 +72,12 @@ PLOT_OUTPUT := /Volumes/Sandisk_Macbook_Pro_1tb/electron_muon_project/plots/out_
 plot:
 	root -l -b -q "src/plot.C(\"$(PLOT_INPUT)\", \"$(PLOT_OUTPUT)\")"
 
+plot_specified:
+	@if [ -z "$(output)" ]; then \
+		echo "ERROR: Please specify output=electrons or output=muons"; \
+		exit 1; \
+	fi
+	root -l -b -q "src/plot.C(\"$(PLOT_INPUT)\", \"$(dir $(PLOT_OUTPUT))$(basename $(notdir $(PLOT_OUTPUT)))_$(output).pdf\")"
 
 
-.PHONY: all clean cleanall dirs run_specified run plot
+.PHONY: all clean cleanall dirs run_specified run plot plot_specified
